# permissions to do edit telemetryrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetryrecord-editor-role
rules:
- apiGroups:
  - run.tanzu.vmware.com.run.tanzu.vmware.com
  resources:
  - telemetryrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - run.tanzu.vmware.com.run.tanzu.vmware.com
  resources:
  - telemetryrecords/status
  verbs:
  - get
  - patch
  - update
