# permissions to do viewer telemetryrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetryrecord-viewer-role
rules:
- apiGroups:
  - run.tanzu.vmware.com.run.tanzu.vmware.com
  resources:
  - telemetryrecords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - run.tanzu.vmware.com.run.tanzu.vmware.com
  resources:
  - telemetryrecords/status
  verbs:
  - get
